benchmarks:
- benchmark_name: ppermute
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 8, ici_size_range: 8}
  warmup_tries: 100
  trace_dir: "/tmp/microbenchmarks/collectives"
  csv_path: "/tmp/microbenchmarks/collectives"
  xla_dump_dir: "/tmp/microbenchmarks/collective/hlo_graphs"
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 8, ici_size_range: 8}
  warmup_tries: 100
  trace_dir: "/tmp/microbenchmarks/collectives"
  csv_path: "/tmp/microbenchmarks/collectives"
  xla_dump_dir: "/tmp/microbenchmarks/collective/hlo_graphs"
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 8, ici_size_range: 8}
  warmup_tries: 100
  trace_dir: "/tmp/microbenchmarks/collectives"
  csv_path: "/tmp/microbenchmarks/collectives"
  xla_dump_dir: "/tmp/microbenchmarks/collective/hlo_graphs"
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 1024, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 8, ici_size_range: 8}
  warmup_tries: 100
  trace_dir: "/tmp/microbenchmarks/collectives"
  csv_path: "/tmp/microbenchmarks/collectives"
  xla_dump_dir: "/tmp/microbenchmarks/collective/hlo_graphs"
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"